// Sample products used to seed the Firebase Realtime Database from the Admin Panel.
// Edit freely — these are styled around a clothing/apparel store ("Maison").

export const sampleProducts = [
  {
    name: "Aria Linen Shirt",
    price: 3499,
    image: "https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=600&q=80",
    description: "A relaxed-fit shirt cut from breathable linen blend. Soft drape, mother-of-pearl buttons, made for warm afternoons.",
    category: "Shirts",
    stock: 24,
    featured: true,
  },
  {
    name: "Nimbus Wool Sweater",
    price: 5999,
    image: "https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=600&q=80",
    description: "Cloud-soft merino wool knit with a ribbed collar. Pairs equally well with denim or tailored trousers.",
    category: "Sweaters",
    stock: 15,
    featured: true,
  },
  {
    name: "Harbor Canvas Tote",
    price: 2799,
    image: "https://images.unsplash.com/photo-1591561954557-26941169b49e?w=600&q=80",
    description: "Heavyweight cotton canvas tote with reinforced handles. Built to carry groceries, books, or a laptop without complaint.",
    category: "Accessories",
    stock: 40,
    featured: true,
  },
  {
    name: "Solstice Denim Jacket",
    price: 6499,
    image: "https://images.unsplash.com/photo-1551028719-00167b16eac5?w=600&q=80",
    description: "A classic trucker silhouette in rigid selvedge denim that softens beautifully with wear.",
    category: "Jackets",
    stock: 12,
    featured: true,
  },
  {
    name: "Quiet Hour Pajama Set",
    price: 4199,
    image: "https://images.unsplash.com/photo-1617137968427-85924c800a22?w=600&q=80",
    description: "Brushed cotton pajama set designed for slow mornings. Includes a button-down top and elastic-waist pants.",
    category: "Loungewear",
    stock: 30,
    featured: false,
  },
  {
    name: "Meridian Leather Belt",
    price: 1899,
    image: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600&q=80",
    description: "Full-grain leather belt with a brushed brass buckle. Ages gracefully over years of daily wear.",
    category: "Accessories",
    stock: 50,
    featured: false,
  },
  {
    name: "Drift Cotton Chinos",
    price: 3299,
    image: "https://images.unsplash.com/photo-1473966968600-fa801b869a1a?w=600&q=80",
    description: "Tapered chinos in stretch cotton twill. Tailored enough for the office, easy enough for the weekend.",
    category: "Pants",
    stock: 22,
    featured: false,
  },
  {
    name: "Lowtide Canvas Sneakers",
    price: 4799,
    image: "https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?w=600&q=80",
    description: "Minimal canvas sneakers with a vulcanized rubber sole. One pair, every outfit.",
    category: "Footwear",
    stock: 18,
    featured: true,
  },
  {
    name: "Hollow Ridge Scarf",
    price: 1599,
    image: "https://images.unsplash.com/photo-1520903920243-00d872a2d1c9?w=600&q=80",
    description: "Lightweight wool-blend scarf woven in a subtle herringbone pattern.",
    category: "Accessories",
    stock: 35,
    featured: false,
  },
  {
    name: "Fieldnote Flannel Shirt",
    price: 3899,
    image: "https://images.unsplash.com/photo-1589310243389-96a5483213a8?w=600&q=80",
    description: "Brushed flannel shirt in a muted plaid. Heavyweight enough for cool evenings, soft from the first wash.",
    category: "Shirts",
    stock: 20,
    featured: false,
  },
  {
    name: "Outpost Puffer Vest",
    price: 5499,
    image: "https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=600&q=80",
    description: "Packable down-alternative vest with a water-resistant shell. Layers under any jacket.",
    category: "Jackets",
    stock: 10,
    featured: false,
  },
  {
    name: "Basin Knit Beanie",
    price: 999,
    image: "https://images.unsplash.com/photo-1576871337622-98d48d1cf531?w=600&q=80",
    description: "Ribbed knit beanie in heavyweight wool. Fitted, not slouchy.",
    category: "Accessories",
    stock: 60,
    featured: false,
  },
];
